name: Build and deploy Jekyll site

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'

    - name: Ruby and Bundler versions
      run: |
        ruby --version
        bundle --version

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --verbose
      
    - name: Build site
      run: bundle exec jekyll build --trace

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
